name: Check semver

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:

jobs:
  check-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Rust Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
        with:
          cache-on-failure: true

      - name: install parity-publish
        run: cargo install parity-publish@0.4.0

      - name: check semver
        run: |
          test -f prdoc/pr_${GITHUB_PR}.prdoc && parity-publish prdoc \
            --since ${{ github.event.pull_request.base.sha }} --validate prdoc/pr_${GITHUB_PR}.prdoc
