name: Check semver

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:

jobs:
  check-publish:
    runs-on: ubuntu-latest
    container:
      image: docker.io/paritytech/ci-unified:bullseye-1.77.0-2024-04-10-v20240408
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 250

      - name: Rust Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
        with:
          cache-on-failure: true

      - name: Rust compilation prerequisites
        run: rustup toolchain install nightly

      - name: install parity-publish
        run: cargo install parity-publish@0.4.1

      - name: check semver
        run: |
          git config --global --add safe.directory '*'
          if [ -f prdoc/pr_$PR.prdoc ]; then
            echo parity-publish prdoc --since $BASE --validate prdoc/pr_$PR.prdoc
            parity-publish prdoc --since $BASE --validate prdoc/pr_$PR.prdoc
          fi
        env:
          PR: ${{ github.event.pull_request.number }}
          BASE: ${{ github.event.pull_request.base.sha }}
